In [10]:
import pandas as pd

In [11]:
local = pd.read_csv('local_result/result.csv')

In [13]:
local.head(9)

,NombreArchivo,idCupon,DNI,AcertividadDNI,Telefono,AcertividadTelefono,idCampania,idUsuario,idEstado,LocalJsonOCR,Azure
0,MarzoCompras_0202072019164448_00043,1000,672658937,0.00,777257672,91.85,4,1,1,"{""dni_cnn"": {""value"": ""672658937""}, ""telefono_...",1
1,MarzoCompras_0202072019164503_00537,1001,80552369,89.50,2726244,98.01,4,1,1,"{""dni_cnn"": {""value"": ""80552369""}, ""telefono_c...",1
2,MarzoCompras_0202072019164503_00546,1002,6650,0.00,9453881,73.68,4,1,1,"{""dni_cnn"": {""value"": ""6650""}, ""telefono_cnn"":...",1
3,MarzoCompras_0202072019164511_00837,1003,424475467,0.00,50254468,81.97,4,1,1,"{""dni_cnn"": {""value"": ""424475467""}, ""telefono_...",1
4,MarzoCompras_EL_B3_20190705154148_00762,1004,47744774,96.28,95306512,96.02,4,1,1,"{""dni_cnn"": {""value"": ""47744774""}, ""telefono_c...",0
5,MarzoCompras_EL_B3_20190705154149_00798,1005,9900757,87.28,5386478,93.14,4,1,1,"{""dni_cnn"": {""value"": ""09900757""}, ""telefono_c...",1
6,MarzoCompras_LV_B2_20190704151228_00879,1006,23849537,0.00,4577793832,0.00,4,1,1,"{""dni_cnn"": {""value"": ""023849537""}, ""telefono_...",1
7,MarzoCompras_MD_B5_20190709165132_00965,1007,70605766,99.36,925054302,90.14,4,1,1,"{""dni_cnn"": {""value"": ""70605766""}, ""telefono_c...",0
8,MarzoCompras_XM_B5_20190710113243_01121,1008,42210749,97.36,951782146,98.99,4,1,1,"{""dni_cnn"": {""value"": ""42210749""}, ""telefono_c...",0

In [8]:
azure = pd.read_csv('azure_result/azure_result.csv')

In [9]:
azure.head()

,NombreArchivo,idCupon,DNI,AcertividadDNI,Telefono,AcertividadTelefono,NombreCompleto,AcertividadNombreCompleto,Direccion,AcertividadDireccion,Distrito,AcertividadDistrito,Correo,AcertividadCorreo,idCampania,idUsuario,idEstado
0,MarzoCompras_0202072019164448_00043,1000,42650934.0,85.714286,977784672,85.714286,Blaudi Idali Raja Revilla.,86.250000,J. Beamin Quiroga 569 German,85.000000,San Martin de porres,86.25,maicusi@hotmail.com,87.5,4,1,1
1,MarzoCompras_0202072019164503_00537,1001,40557762.0,90.000000,927136744,85.000000,,0.000000,&- Sou Juau Bautista # 332 - Palo,86.000000,Son Mortin de tones,86.25,Micasu-800/Hotmail.Com,87.5,4,1,1
2,MarzoCompras_0202072019164503_00546,1002,8642202.0,87.916667,995382267,87.916667,CAROLINA Cde los MERINO,85.833333,CALLE LOS HOENES # 170 unit. INs. INFANTAS,86.000000,LOS OLIVOS,90.00,CAROLINACHIO10/0AOLMAIL.CO.,85.0,4,1,1
3,MarzoCompras_0202072019164511_00837,1003,NaN,0.000000,98083440,86.666667,JACK cline Min DOa BEcerra,86.250000,Jr. JOSE BAITa. 18 106 Urb . Sam Juanito,86.750000,SAn Juan DE MINAFTons,87.50,soJordyvaGmail.com,89.0,4,1,1
4,MarzoCompras_EL_B3_20190705154148_00762,1004,4714974.0,85.000000,953065112,86.666667,Mizer SiLUA medina,87.500000,PASAJe: LIBERTAD # 102 ERMITAND,86.666667,Inde Pendencia,87.50,NaN,0.0,4,1,1